config/routes.rb
Rails.application.routes.draw do
  resources :myschedules
  resources :schedules
  get 'welcome/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myschedule.rb
class Myschedule < ApplicationRecord
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  def day_enum
    [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
    21,22,23,24,25,26,27,28,29,30,31]
  end
  def month_enum
    ['Janeiro','Fevereiro','Março', 'Abril', 'Maio', 'Junho',
    'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
  end
  def year_enum
    [2017,2018,2019,2020]
  end
  def service_enum
    ['Corte','Hidratação','Escova','Cauterização', 'Progressiva']
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :myschedules
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  def after_sign_in_path_for(resource)
    if current_user.admin = true
      "/admin"
    else
      schedules_path
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/myschedules_controller.rb
class MyschedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_myschedule, only: [:show, :edit, :update, :destroy]
  $schedule_id = nil
  # GET /myschedules
  # GET /myschedules.json
  def index
    @user = current_user
    @myschedules = @user.myschedules.all
  end

  # GET /myschedules/1
  # GET /myschedules/1.json
  def show
  end

  # GET /myschedules/new
  def new
    @myschedule = Myschedule.new
    @time = params[:time]
    @day = params[:day]
    @month = params[:month]
    @year = params[:year]
    $schedule_id = params[:schedule_id]
    @service = params[:service]
  end

  # GET /myschedules/1/edit
  def edit
  end

  # POST /myschedules
  # POST /myschedules.json
  def create
    @user = current_user
    @myschedule = @user.myschedules.build(myschedule_params)

    respond_to do |format|
      if @myschedule.save
        Schedule.find($schedule_id).destroy
        format.html { redirect_to @myschedule, notice: 'Seu horário foi marcado' }
        format.json { render :show, status: :created, location: @myschedule }
      else
        format.html { render :new }
        format.json { render json: @myschedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myschedules/1
  # PATCH/PUT /myschedules/1.json
  def update
    respond_to do |format|
      if @myschedule.update(myschedule_params)
        format.html { redirect_to @myschedule, notice: 'Myschedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @myschedule }
      else
        format.html { render :edit }
        format.json { render json: @myschedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myschedules/1
  # DELETE /myschedules/1.json
  def destroy
    @schedule = Schedule.new(time: @myschedule.time, day: @myschedule.day, month: @myschedule.month, year: @myschedule.year, service: @myschedule.service)
    @schedule.save
    @myschedule.destroy
    respond_to do |format|
      format.html { redirect_to myschedules_url, notice: 'Seu horário foi desmarcado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myschedule
      @myschedule = Myschedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myschedule_params
      params.require(:myschedule).permit(:time, :day, :month, :year, :user_id, :service)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:time, :day, :month, :year, :service)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myschedules_helper.rb
module MyschedulesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<body class="<%= controller.controller_name%>">

<html>
  <head>
    <title>BeautySchedule</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <header>
          <div class="wrapper">
              <h1>BeautySchedule<span class="color"></span></h1>
              <nav>
                  <ul>
                      <% if current_user %>
                          <li><%= link_to 'Horários disponíveis', schedules_path %></li>
                          <li><%= link_to 'Meus horários', myschedules_path %></li>
                          <li><%= link_to('Sair', destroy_user_session_path, method: :delete) %> </li>
                      <% else %>
                          <li><a href="/users/sign_in">Entrar</a></li>
                          <li><a href="/users/sign_up">Criar conta</a></li>
                      <% end %>
                  </ul>
              </nav>
          </div>
      </header>

      <%- flash.each do |name, msg| -%>
        <div class="custom-alert">
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <%- end -%>
    <%= yield %>

  </body>
</html>

app/views/myschedules/_form.html.erb
<%= form_with(model: myschedule, local: true) do |form| %>
  <% if myschedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(myschedule.errors.count, "error") %> prohibited this myschedule from being saved:</h2>

      <ul>
      <% myschedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>Hora</br>
    <%= form.text_field :time, :value => params[:time], :readonly => true %>
  </div>

  <div class="field">
    <br>Dia</br>
    <%= form.text_field :day, :value => params[:day], :readonly => true %>
  </div>


  <div class="field">
    <br>Mês</br>
    <%= form.text_field :month, :value => params[:month], :readonly => true %>
  </div>

  <div class="field">
    <br>Ano</br>
    <%= form.text_field :year, :value => params[:year], :readonly => true %>
  </div>

  <div class="field">
    <br>Serviço</br>
    <%= form.text_field :service, :value => params[:service], :readonly => true %>
  </div>

  <div class="actions">
    <br><%= form.submit "Marcar horário" %></br>
  </div>

<% end %>

app/views/myschedules/index.html.erb
<div class="myschedule">
<h4>Horários marcados</h4>
    <table class="center">
      <thead>
        <tr>
          <th>Hora</th>
          <th>Dia</th>
          <th>Mês</th>
          <th>Ano</th>
          <th>Serviço</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @myschedules.order(:day, :time).each do |myschedule| %>
          <tr>
            <td><%= myschedule.time %></td>
            <td><%= myschedule.day %></td>
            <td><%= myschedule.month %></td>
            <td><%= myschedule.year %></td>
            <td><%= myschedule.service %></td>
            <td><%= link_to ' Detalhes ', myschedule %></td>
            <td><%= link_to ' Desmarcar ', myschedule, method: :delete, data: { confirm: 'Você tem certeza que deseja desmarcar?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/myschedules/new.html.erb
<h4>Marcar horário</h4>
<%= render 'form', myschedule: @myschedule %>
<div style="text-align:center">      
  <%= link_to 'Voltar', schedules_path %>
</div>

app/views/myschedules/show.html.erb
<div class="show">
  <p>
    <strong>Hora:</strong>
    <%= @myschedule.time %>
  </p>

  <p>
    <strong>Dia:</strong>
    <%= @myschedule.day %>
  </p>

  <p>
    <strong>Mês:</strong>
    <%= @myschedule.month %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= @myschedule.year %>
  </p>

  <p>
    <strong>Serviço:</strong>
    <%= @myschedule.service %>
  </p>


  <%= link_to 'Voltar', myschedules_path %>
</div>

app/views/schedules/index.html.erb
<div class="schedule">
<h4>Horários disponíveis</h4>
    <table class="center">
      <thead>
        <tr>
          <th>Hora</th>
          <th>Dia</th>
          <th>Mês</th>
          <th>Ano</th>
          <th>Serviço</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @schedules.order(:day, :time).each do |schedule| %>
          <tr>
            <td><%= schedule.time %></td>
            <td><%= schedule.day %></td>
            <td><%= schedule.month %></td>
            <td><%= schedule.year %></td>
            <td><%= schedule.service%></td>
            <td><%= link_to 'Detalhes', schedule %></td>
            <td><%= link_to 'Marcar Horário', new_myschedule_path(time: schedule.time, day: schedule.day, month: schedule.month, year: schedule.year, schedule_id: schedule.id, service: schedule.service)  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/schedules/show.html.erb
<div class="show">
  <p>
    <strong>Hora:</strong>
    <%= @schedule.time %>
  </p>

  <p>
    <strong>Dia:</strong>
    <%= @schedule.day %>
  </p>

  <p>
    <strong>Mês:</strong>
    <%= @schedule.month %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= @schedule.year %>
  </p>

  <p>
    <strong>Serviço:</strong>
    <%= @schedule.service %>
  </p>

  <%= link_to 'Voltar', schedules_path %>
</div>

app/views/welcome/index.html.erb
<div class="welcome">
</div>